spring:
  application:
    name: command-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/command-service
server:
  port: 8081
axon:
  axonserver:
    enabled: false
  serializer:
    messages: jackson
    events: jackson
    general: jackson
  mongo:
    database-name: command-service
    token-store:
      enabled: true
    saga-store:
      enabled: false
    event-store:
      enabled: true
  kafka:
    bootstrap-servers: localhost:19092
    client-id: axon-kafka-test
    default-topic: axon.events
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: axon-kafka-test
      event-processor-mode: pooled_streaming

